# Generated by Django 4.1 on 2022-08-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_datacollected_alter_customuser_first_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='datacollected',
            new_name='DataCollection',
        ),
    ]
