# Generated by Django 4.1 on 2022-08-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_rename_datacollected_datacollection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataCollection',
            new_name='datacollected',
        ),
    ]
