# Generated by Django 4.1 on 2022-08-27 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0005_rename_datacollected_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data',
            new_name='data_collected',
        ),
    ]
