# Generated by Django 4.1 on 2022-09-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0006_rename_data_data_collected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_collected',
            name='browser_fonts',
        ),
        migrations.RemoveField(
            model_name='data_collected',
            name='canvas',
        ),
        migrations.RemoveField(
            model_name='data_collected',
            name='canvas_totaltime',
        ),
        migrations.RemoveField(
            model_name='data_collected',
            name='plugins',
        ),
        migrations.RemoveField(
            model_name='data_collected',
            name='plugins_totaltime',
        ),
        migrations.RemoveField(
            model_name='data_collected',
            name='webgl',
        ),
        migrations.RemoveField(
            model_name='data_collected',
            name='webgl_totaltime',
        ),
    ]
