# Generated by Django 4.1 on 2022-09-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0007_remove_data_collected_browser_fonts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_collected',
            name='Uid',
            field=models.CharField(default='Id not given', max_length=400),
        ),
    ]
