# Generated by Django 4.1 on 2022-09-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0008_data_collected_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_collected',
            name='ip',
            field=models.CharField(blank=True, default='something', max_length=40, null=True),
        ),
    ]
